version: "3.1"
services:
  postgres:
    image: "postgres:latest"
    labels:
      wizard: "wizard"
    restart: always
    environment:
      POSTGRES_USER: zzh
      POSTGRES_PASSWORD: "123"
    networks:
      - archie_net
    volumes:
      - ./docker/db/postgres.init.sql:/docker-entrypoint-initdb.d/postgres.init.sql

  redis:
    image: redis:latest
    labels:
      wizard: "wizard"
    restart: always
    volumes:
      - redis_data:/var/lib/redis/data
    networks:
      - archie_net

  nginx:
    image: nginx:latest
    labels:
      wizard: "wizard"
    volumes:
      - ./docker/configs/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - archie_net
    ports:
      - "8080:8080"

  archie:
    build: .
    image: "archie"
    restart: always
    labels:
      wizard: "wizard"
    depends_on:
      - nginx
      - postgres
      - redis

    ports:
      - "3000:3000"
    networks:
      - archie_net
    tty: true

networks:
  archie_net:
    external:
      name: archie_net

volumes:
  postgres_data:
    external: true
  redis_data:
    external: true
