version: '3.1'
services:
  postgres:
    image: 'postgres:latest'
    labels:
      wizard: 'wizard'
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: zzh
      POSTGRES_PASSWORD: 123
    volumes:
      - ./docker/db/postgres.init.sql:/docker-entrypoint-initdb.d/postgres.init.sql

  redis:
    image: redis:latest
    ports:
      - "6379:6379"graogh
    labels:
      wizard: 'wizard'
    restart: always
    volumes:
      - ./docker/redis_data:/var/lib/redis/data
      - ./docker/configs/redis.conf:/etc/redis/redis.conf
    command:
      - /bin/bash
      - -c
      - |
        mkdir -p /usr/local/var/db/redis/
        redis-server /etc/redis/redis.conf

volumes:
  postgres_data:
    external: true
  redis_data:
    external: true