name: website lint & run tests & deploy
on:
  - push

jobs:
  upload-image:
    name: upload docker image to cloud
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: scp docker-compose.yml to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          username: ${{ secrets.DEPLOY_SERVER_USER }}
          password: ${{ secrets.DEPLOY_SERVER_PASSWORD }}
          port: ${{ secrets.DEPLOY_SERVER_SSH_PORT }}
          source: './docker-compose.yml,./docker'
          target: '/root/mist/archie'
          timeout: 120s
          rm: true

      - name: docker login
        run: docker login --username=${{ secrets.TENCENT_YUN_USERNAME }} --password ${{ secrets.TENCENT_YUN_PASSWORD }}

      - name: build docker image
        run: docker build -t archie .

      - name: tag the image & push the image to cloud
        run: |
          docker tag $(docker images -q --filter reference=archie) ${{ secrets.WEBSITE_IMAGE_NAME }}
          docker push ${{ secrets.WEBSITE_IMAGE_NAME }}

  pull-image:
    needs: [upload-image]
    name: pull image from cloud
    runs-on: ubuntu-latest
    steps:
      - name: deploy website
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          username: ${{ secrets.DEPLOY_SERVER_USER }}
          password: ${{ secrets.DEPLOY_SERVER_PASSWORD }}
          port: ${{ secrets.DEPLOY_SERVER_SSH_PORT }}
          script: |
            docker network create archie_net
            docker login --username=${{ secrets.TENCENT_YUN_USERNAME }} --password ${{ secrets.TENCENT_YUN_PASSWORD }}
            docker rm -f ${{ secrets.WEBSITE_CONTAINER_NAME }}
            docker rmi -f ${{ secrets.WEBSITE_IMAGE_NAME }}
            docker pull ${{ secrets.WEBSITE_IMAGE_NAME }}
            docker stop ${{ secrets.WEBSITE_CONTAINER_NAME }}
            cd /root/mist/archie
            docker-compose down
            docker-compose up -d
